# This workflow sets up and runs MSBuild and VSTest
# to build and test a Visual Studio solution.

name: Build and Test

on:
  push:
    branches:
      - master
      - test/*
      - feature/*
      - bugfix/*

  pull_request:
    branches:
      - master
      - test/*
      - feature/*
      - bugfix/*

jobs:
  run-msbuild:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2022
    name: Run MSBuild and VSTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout_code

      - uses: nuget/setup-nuget@v2
        with:
         nuget-version: '6.x'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 3.1.x
          cache: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.x
          cache: true

      - name: Restore nuget
        id: run_nuget
        working-directory: ${{ github.workspace }}
        run: nuget.exe restore .\AdaptiveShell.sln

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1
        id: setup_msbuild

      - name: Run MSBuild
        id: run_msbuild
        working-directory: ${{ github.workspace }}
        run: msbuild .\AdaptiveShell.sln /property:Configuration=${{ matrix.configuration }} /p:Platform=x64

      - name: Setup VSTest path
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest
